add support for d symbol demangling
KDAB/perfparser pull request #21
Opened 2021-09-15 13:00 UTC by lievenhey

2021-09-15 15:07 UTC, sandsmark commented
Would it make sense to either support piping things through external scripts (a la llvm-symbolizer) or have proper plugins?

It seems awkward manually hardcoding a set of in essence plugins that live half in-tree, half out-of-tree.

It might make sense to have some heuristics for what symbols to pass to the rust or d demanglers, passing every symbol through them seems like unnecessary overhead when 99.9% of the symbols hotspot is going to encounter are neither.

2021-09-16 18:46 UTC, milianw requested changes
generally this looks good to me.

and no, we don't want to spawn external processes, as that's usually quite slow. a library call otoh is fast, and they will have fast-path returns for bad input. we can always optimize this later if need be.

meaning again: I'm perfectly fine with the proposed approach of this patch, it looks good!

2021-09-16 18:46 UTC, milianw commented on app/demangler.cpp
> +    if (prefix.isEmpty()) {
use `strcmp(string, prefix.constData()) == 0`;

2021-09-16 18:46 UTC, milianw commented on app/demangler.cpp
> +    const QVector<DemangleLib> demangleLibs = {
don't use a QVector, just use an initializer list, i.e. just `const auto demangleLibs = {...}`

2021-10-26 09:02 UTC, lievenhey commented
I had completely forgotten this pull request. Fixed those two requests

2021-10-27 09:09 UTC, milianw requested changes

2021-10-27 09:09 UTC, milianw commented on app/demangler.cpp
> +    struct DemangleLib {
personally I think it's much simpler to just call the `loadDemangleLib` directly here - then most of this boilerplate can be removed again.

i.e. remove `DemangleLib` and `demangleLibs` and the for loop, and replace it by these two lines:

loadDemangleLib(QStringLiteral("rustc_demangle"), "rustc_demangle", QByteArrayLiteral("_R"));
loadDemangleLib(QStringLiteral("d_demangle"), "demangle_symbol", QByteArrayLiteral("_RD));

2021-10-27 09:09 UTC, milianw commented on app/demangler.cpp
> +/* Demangler spezification
typo: specification

2021-11-25 19:24 UTC, milianw approved these changes

2021-11-25 19:24 UTC, merged