add check for build id
KDAB/perfparser pull request #24
Opened 2022-05-09 11:11 UTC by lievenhey

when searching in extra path, ... the build id is not checked which
could lead to problems while creating a backtrace.

This patch add a check for the build id in appPath and extraLibPaths

2022-10-11 09:22 UTC, lievenhey commented
I am not sure if I used the qScopeGuard correctly. But based on the output of
```c++
#include <QCoreApplication>
#include <QScopeGuard>
#include <iostream>

struct Obj {
    Obj() {std::cout << "ctor" << std::endl;}
    ~Obj() {std::cout << "dtor" << std::endl;}
};

Obj test() {
    auto t = qScopeGuard([]{std::cout << "test" << std::endl;});

    return Obj();
}

int main(int argc, char *argv[])
{
    auto q = test();
    std::cout << "end" << std::endl;

    return 0;
}
```
```
ctor
test
end
dtor
```
I assume I did it correctly.

2022-10-11 11:21 UTC, dfaure-kdab commented
> I am not sure if I used the qScopeGuard correctly. But based on the output of
> I assume I did it correctly.

The creation/deletion of one or more Obj instances in this code depends on the C++ version (guaranteed copy elision in C++17) and on the RVO optimization...

Add `if (argc>1) return Obj(another_param);` and you'll get a different result, even if argc==1, because this will disable RVO...

2022-10-11 11:29 UTC, dfaure-kdab commented
OK in practice I can't really write a testcase that leads to a different result though :-)

2022-10-12 14:10 UTC, milianw requested changes, later dismissed
usage of `qScopeGuard` is fine in your code, the `QByteArray` will be constructed and then copy the data before the guard gets destroyed and thus calls `elf_end`

2022-10-12 14:10 UTC, milianw commented on app/perfsymboltable.cpp
> +static QByteArray getBuildIdFromFile(const QFileInfo& path)
remove `get` prefix

2022-10-12 14:10 UTC, milianw commented on app/perfsymboltable.cpp
> +    int fd = file.handle();
inline below

2022-10-12 14:10 UTC, milianw commented on app/perfsymboltable.cpp
> +    Elf* elf = elf_begin(fd, ELF_C_READ, NULL);
```
auto elf = elf_begin(file.handle(), ELF_C_READ, nullptr);
```

2022-10-12 14:10 UTC, milianw commented on app/perfsymboltable.cpp
> +    const void* buildId;
= nullptr;

2022-10-18 11:41 UTC, milianw approved these changes
lgtm, thanks

2023-05-23 09:15 UTC, merged