reduce floodding debug output
KDAB/perfparser pull request #30
Opened 2023-10-24 22:09 UTC by GitMensch

suppress debug output for invalid address passed to `memoryRead` if it is identical to the last recognized invalid one

2023-10-29 19:19 UTC, milianw requested changes

2023-10-29 19:19 UTC, milianw commented on app/perfunwind.cpp
> +        static Dwarf_Addr last_invalid_addr;
don't use a static, make it a member function local to the `UnwindInfo` struct above

2023-10-29 19:19 UTC, milianw commented on app/perfunwind.cpp
> +        static Dwarf_Addr last_invalid_addr;
oh and use camelCase  instead of snake_case

2023-11-05 18:13 UTC, GitMensch commented
casing fixed and moved to `UnwindInfo` as requested; note: this obviously adds much more data (one for each `UnwindInfo` - but I don't know how often / much of those we allocate) and is "global"; I don't know if the original "shows less often the same entry" is now better (because we get back to the same entry later and already marked it as invalid) or not as good as the original "only cache the very last entry, so you don't get the same output over and over".

2023-11-10 19:01 UTC, milianw requested changes

2023-11-10 19:01 UTC, milianw commented on app/perfunwind.h
> +        Dwarf_Addr lastInvalidAddr;
missing initializer a few lines above

2023-11-10 19:02 UTC, milianw commented
> casing fixed and moved to `UnwindInfo` as requested; note: this obviously adds much more data (one for each `UnwindInfo` - but I don't know how often / much of those we allocate)

We have one of these per process, this is really a tiny amount of data.

> and is "global"; I don't know if the original "shows less often the same entry" is now better (because we get back to the same entry later and already marked it as invalid) or not as good as the original "only cache the very last entry, so you don't get the same output over and over". _(note to **self**: nice for testing once this lands is named "DOKU_AKS")_

I don't quite know what you are saying here. It sounds like you didn't actually test whether this works as desired? Can you please do that then?

2023-11-10 20:17 UTC, GitMensch commented
For the last test I'll create an "update perfparser" PR to Hotspot after doing the requested changes, if I can't get the binary created in my dev environment working on the machine where I have problems (that only uses the appimages).

In any case:
Could you add some minimal CI here that checks that everything compiles and passes quality checks (copy over from Hotspot) and possibly make the perfparser binary available that "matches" the appimage environment - or would this make upstream work hard?

2024-01-02 10:30 UTC, GitMensch commented
I've added the missing init (I think) and then tested the resulting hotspot-perfparser by replacing the one found in the appimage with this one, strangely instead of

```
Invalid memory read requested by dwfl fffffffffffffff9
Invalid memory read requested by dwfl fffffffffffffff9
Invalid memory read requested by dwfl fffffffffffffff9
Invalid memory read requested by dwfl fffffffffffffff9
Invalid memory read requested by dwfl fffffffffffffff9
Invalid memory read requested by dwfl fffffffffffffff9
Invalid memory read requested by dwfl fffffffffffffff9
Invalid memory read requested by dwfl fffffffffffffff9
Invalid memory read requested by dwfl fffffffffffffff9
Invalid memory read requested by dwfl fffffffffffffff9
```

I have zero occurrences of that, while I've expected one.

2024-01-02 16:02 UTC, GitMensch commented
Hm, not sure if there's something broken with this PR or with my build, but using an existing appimage (extracted) and copy-paste a hotspot-perfparser from this build breaks the flamegraph. That needs to be checked before a possible pull.

2024-01-10 19:49 UTC, GitMensch commented
I see no reason why that should break hotspot's flamegraph and I've checked that it does produce less output, so... please review/pull.

2024-01-15 08:35 UTC, GitMensch commented
Still get a bunch of those outputs with Hotspot ;-)
Friendly ping @milianw for re-review, the requested changes were done two weeks ago.

2024-01-17 18:44 UTC, milianw approved these changes

2024-01-17 18:45 UTC, milianw commented
so, code wise this looks good. but:

- you said it breaks stuff? is that really the case? have you investigated that?
- and are you saying this isn't enough and you still get "a bunch of those outputs" with this patch, meaning it's not enough?

2024-01-17 23:17 UTC, GitMensch commented
I had broken results, but this likely comes from my Frankenbuild, I don't see how those coffee changes would be the reason for that.

I did see much less warnings with using that (one per different address), but that's expected.

2025-05-29 15:45 UTC, milianw approved these changes
can you rebase and resubmit, I guess it's fine if it reduces debug floods for you

2025-05-29 16:27 UTC, GitMensch commented
Thank you, that should already help a lot. Rebasing done.

2025-06-04 19:40 UTC, milianw approved these changes

2025-06-04 19:40 UTC, merged