forward inline information
KDAB/perfparser pull request #31
Opened 2023-12-05 14:26 UTC by lievenhey

This should allow hotspot to show inline information. Currently it doesn't work for every symbol.
If you see something like this:
![grafik](https://github.com/KDAB/perfparser/assets/82457690/9796a3cc-b4dc-4f1f-b90d-232e13bf0dc6)
in the flamegraph, it doesn't work. The parent frame will have the inline information, but not top child.

2023-12-05 14:38 UTC, lievenhey commented
see https://github.com/KDAB/hotspot/pull/568

2023-12-05 18:24 UTC, milianw requested changes
don't we have tests for this part here too that should be extended then? e.g. in TestPerfData and PerfParserTestClient you should also get this data and verify that this works as you expect it to

2023-12-05 18:24 UTC, milianw commented on app/perfunwind.cpp
> +    return stream << symbol.name << symbol.binary << symbol.path << symbol.isKernel << symbol.isInline << symbol.relAddr << symbol.size << symbol.actualPath;
please always add the new data at the end such that the format stays somewhat compatible to before

2023-12-05 18:24 UTC, milianw commented on app/perfsymboltable.cpp
> +        return insertSubprogram(cudie, top, entry, offset, size, relAddr, binaryId, binaryPathId, actualPathId, callLocationId, isKernel, true);
are you sure this is the right place to make the inline vs. non-inline decision? see `PerfSymbolTable::parseDwarf` which gets a clear list of inlined DIEs and the subprogram die - I think that's the level where this should be handled, no?

2023-12-07 10:11 UTC, lievenhey commented on app/perfsymboltable.cpp
> +        return insertSubprogram(cudie, top, entry, offset, size, relAddr, binaryId, binaryPathId, actualPathId, callLocationId, isKernel, true);
`PerfSymbolTable::parseDwarf` calls `PerfSymbolTable::handleDie` so I think its fine.

2023-12-14 19:25 UTC, milianw commented
> don't we have tests for this part here too that should be extended then? e.g. in TestPerfData and PerfParserTestClient you should also get this data and verify that this works as you expect it to

this isn't done yet

2024-01-02 14:13 UTC, milianw approved these changes

2024-01-08 13:42 UTC, lievenhey commented
now it is done. Somewhat crude but working.

2024-01-10 09:29 UTC, merged